### ISSUE TITLE
[Feature request] Переключатель в шторке уведомлений.

### ISSUE THREAD

**Issue by KDBal** [dovecoteescapee/ByeDPIAndroid#1]
Здравствуйте. Не могли бы Вы добавить перелючатель в шторку уведомлений для быстрого включения/включения сервиса?

**Comment by dovecoteescapee** [comment]
Есть в планах, добавлю после того, как найдётся время первоочерёдные исправления

**Comment by bezuhv** [comment]
Это важная штука, не понимаю почему сразу не делают...

**Comment by mewforest** [comment]
Согласен, удобная штука, чтобы не лезть - открывать приложение каждый раз. 

Спасибо автору за труды!

**Comment by sherichev** [comment]
> Это важная штука, не понимаю почему сразу не делают...

так могли раньше всех сделать
