### ISSUE TITLE
Сменить дефолтный DNS с 1.1.1.1 на 8.8.8.8

### ISSUE THREAD

**Issue by develux44** [dovecoteescapee/ByeDPIAndroid#106]
### What problem does your proposal solve? / Какую проблему решает ваше предложение?

Ютуб начинает работать как минимум на Ростелекоме

### Describe the solution you'd like / Опишите решение, которое вы предлагаете

Сменить дефолтный DNS сервер на 8.8.8.8

### Describe alternatives you've considered / Опишите альтернативные варианты, которые вы рассматривали

Сменить DNS на 8.8.4.4

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] I have verified that this feature does not already exist / Я убедился(ась), что эта функция еще не существует

**Comment by Arksault** [comment]
у меня и с дефолтными работало до вчерашнего дня. сейчас же не грузит ничего... мб они всё таки додумались закрыть дыры

**Comment by dovecoteescapee** [comment]
> Сменить дефолтный DNS сервер на 8.8.8.8

Честно говоря, не вижу причин для этого. Сам 1.1.1.1, а удачность ip, который вам возвращает DNS зависит от многих факторов

> UI editor > Desync method: Fake
> Split position: 1

При split position: 1, fake должен работать так же, как disorder. Проблема скорее именно в позиции, поменяю стандартную на 1 или 2

**Comment by Arksault** [comment]
> поменяю стандартную на 1 или 2

Может в приложении сделать фидбэк? Небольшой. Кнопку _работает_ или _не работает_ и поле в котором нужно указать провайдера. После нажатия _отправить_ будет происходить отправка данных с настройками и информацией о провайдере.

**Comment by kda2495** [comment]
При split position 3 все работает, на split position 2 не открывается тот же rutracker. Оператор МТС.

**Comment by DimaKors13** [comment]
дом.ру заработало с настройками
DNS: 1.1.1.1
UI editor > Desync method: Fake
Split position: 1

**Comment by develux44** [comment]
Вчера Ростелеком и на 1, и на 2, и на 3 падал, я думаю он адаптируется как то, разные DNS тоже не помогали
Возможно есть смысл каждый раз рандомные значения из [1, 2, 3] и списка DNS серверов выбирать?

**Comment by nik-fray** [comment]
> При split position 1 и 3 все работает, на split position 2 не открывается тот же rutracker. Оператор МТС.

А можете подсказать настройки? Прокси или впн и все остальные, которые меняли?
МТС НН 
при дефолтных выдает ошибку подключения к ютьбу. Ставлю прокси, грузится меню, но не грузятся видео... Пробовал рандомно менять настройки, не помогает)

**Comment by Arksault** [comment]
> А можете подсказать настройки

можешь рискнуть

DNS: 77.88.8.8 или оставить 8.8.4.4
UI editor > Desync method: Fake
Split position: 1 или 2 а может и 3

пробуй, комбинируй
