### ISSUE TITLE
Перестает работать через определенное время

### ISSUE THREAD

**Issue by Deimos36Rus** [dovecoteescapee/ByeDPIAndroid#107]
### Describe the bug / Описание ошибки

1.1.0 Обход блокировок работает только определенное время. У некоторых пользователей время разрыва малое, плюс у них дисконнектит. У меня по другому. Может пол часа, может час, может больше проработать. В приложении показывается коннектед, т.е. не рвется, но по факту обход перестает работать. Будто приложение в сон уходит, хотя экономию энергии я выключил. Режим работы VPN. Пробовал разные конфиги и разные настройки. Обходы работают, но всегда не особо долго. Интернет максимально стабильный.
1.1.1 тестирую. Пока отработало 6 часов. Полет нормальный.
UPD 1.1.1 тоже отлетает, но прям сильно дольше работает.
UPD 1.2.0 пока тестирую.

### To Reproduce / Как воспроизвести

Просто использовать приложение с разными конфигами.

### Expected behavior / Ожидаемое поведение

Работа 24/7

### Environment / Окружение

-Приставка
-UGOOS AM6 PLUS
-Прошивка Android TV slimBOXtv 54.16
-Android 9
-Приложение SmartTube
-ByeDPI version: 1.1.0/1.1.1

### Additional context / Дополнительная информация

На приставке еще обрабатывается музыкальный дискорд бот в Termux, но он никогда не уходит в сон даже с экономией энергии и реконнектится, когда обход блокировок перестает работать. Т.е. бот продолжает работает после своего реконнекта, но перестает обрабатывать ссылки на ютуб. Хотелось бы, чтобы DPI также работал как Termux, без отвалов, 24/7. 

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] This is not a question, feature request, or general feedback / Это не вопрос, предложение новой функциональности или общий отзыв

**Comment by ftugit** [comment]
А я думал, что что-то не правильно настроил и постоянно экспериментирую пытаясь получить проблему

**Comment by Deimos36Rus** [comment]
В данный момент тестирую новую 1.1.1. Уже раз отлетело. Хотя работает уже дольше. Пробую с другими настройками.

**Comment by Deimos36Rus** [comment]
Ночью 1.1.1 снова отлетела. Хотя опять же показывает коннектед. В процессах время приложения/службы идет.

**Comment by ftugit** [comment]
> Ночью 1.1.1 снова отлетела. Хотя опять же показывает коннектед. В процессах время приложения/службы идет.

Я скажу больше - при аналогичных настройках в одной сети иногда vpn вообще не работает пока не сделаю жесткое закрытие приложения. Точнее работает, но залоченный ютуб не говорит, а некоторые сайты бесконечно грузятся. Возможно метод не удачный выбрал, но он единственный работает и на мобильном интернете включительно.

**Comment by Deimos36Rus** [comment]
> Я скажу больше - при аналогичных настройках в одной сети иногда vpn вообще не работает пока не сделаю жесткое закрытие приложения. Точнее работает, но залоченный ютуб не говорит, а некоторые сайты бесконечно грузятся. Возможно метод не удачный выбрал, но он единственный работает и на мобильном интернете включительно.
Тоже иногда бывает такое, но мне помогает передернуть дисконнект/коннект и вроде все заводится. Обычно когда настройки перебираю на всякий случай передергиваю. Но это уже мелочи. Главное, чтобы не отлетало.

1.1.1 долго не продержалась. Только уехал на выходные из дома днем, к вечеру уже отвалилось.
Поставил 1.2.0. Тестирую.

**Comment by Deimos36Rus** [comment]
1.2.0 на fake методе работает без сбоев. split может отлетать. остальные методы либо не работают (лично у меня), либо отлетают быстрее, чем split. Пока использую fake в связке с указанием адресов ютуба через список. И другие приложения работают нормально, и ютуб не отлетает.

**Comment by KaMaToZzz** [comment]
> 1.2.0 на fake методе работает без сбоев. split может отлетать. остальные методы либо не работают (лично у меня), либо отлетают быстрее, чем split. Пока использую fake в связке с указанием адресов ютуба через список. И другие приложения работают нормально, и ютуб не отлетает.

Можете показать настройки? Вообще не работает при различных настройках почему-то...

**Comment by Deimos36Rus** [comment]
> Можете показать настройки? Вообще не работает при различных настройках почему-то...

Бесполезно показывать. У меня местный городской провайдер. От стока там только метод fake, ttl of fake packets 7. sni github.com. Плюс в список загнал только адреса ютуба, чтобы у меня остальные приложения не ломались. VPN режим. Прокси не использую. Если будете использовать режим прокси, его надо вбивать в настройки ютуба. Впн наботает на все сразу, кроме списка.

**Comment by Kirihi147** [comment]
Обход блокировки dpi в браузере работает стабильно. Но с ютубом у меня не так. Работает около 1,5 минуты, далее буфера хватает до 2 минут с начала просмотра(начиная с места просмотра видео, то есть необязательно с 00:00) и перестаёт грузить с нормальной скоростью. Также, если включить автозапуск byedpi в настройках приложений, обход блокировки ютуб длится дольше, около 6-7 минут. Качество могу ставить то, что позволяет мой интернет, то есть во время того, как обход блокировки ютуб ещё работает, скорость соединения максимальная. Пробовал разные конфиги, результат одинаковый - работает первые несколько минут, а далее скорость падает / блокировка снова начинает действовать.
У меня соединение тоже не пропадает. Написано "connected" всегда.
Из экономии батареи приложение исключил.
Версия byedpi - 1.2.0

**Comment by ThaiCat** [comment]
1.2.0 с некоторым шансом иногда спустя несколько часов, иногда несколько дней у меня перестает работать тоже. При этом также перестает работать кнопка 'disconnect', решается только перезагрузкой телефона. Если использовать настоящий впн в это время, негативных эффектов на него нет, идентичное поведение как при незапущенной службе byedpi.
