### ISSUE TITLE
При установке split position 2 не работает интернет

### ISSUE THREAD

**Issue by kda2495** [dovecoteescapee/ByeDPIAndroid#109]
### Describe the bug / Описание ошибки

В версии 1.1.1 по-умолчанию параметр split position установлен на 2. При такой установке не работает интернет. Проверил на 2 разных устройствах. При установке этого параметра на 1 или 3 все работает.

### To Reproduce / Как воспроизвести

Установить split position на 2.

### Expected behavior / Ожидаемое поведение

Все работает.

### Environment / Окружение

**Smartphone / Смартфон:**
- Device: [Xiaomi Redmi Note 12S, Honor X7b]
- Android version: [14]
- ByeDPI version: [1.1.1]

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] This is not a question, feature request, or general feedback / Это не вопрос, предложение новой функциональности или общий отзыв

**Comment by kda2495** [comment]
Думаю, лучше по-умолчанию установить значение split position на 1.

**Comment by dovecoteescapee** [comment]
Подскажите, какой у вас провайдер? МГТС?

**Comment by kda2495** [comment]
> Подскажите, какой у вас провайдер? МГТС?

Мобильный МТС.

**Comment by dovecoteescapee** [comment]
Изменил стандартное значение на 1
