### ISSUE TITLE
Добавить опцию выборочных доменов

### ISSUE THREAD

**Issue by yozhigf** [dovecoteescapee/ByeDPIAndroid#11]
Добавьте, пожалуйста, в программу выбор отдельных доменов. Это опция в byedpi:

-H, --hosts <file|:string>
    Ограничить область действия параметров списком доменов
    Домены должны быть разделены новой строкой или пробелом

**Comment by eddiezato** [comment]
Приложению определенно очень нужна поддержка hosts. Нашел стратегию обхода блокировки youtube, но при этом отваливается отправка голосовых сообщений в whatsapp.

**Comment by artemiux** [comment]
Now in [1.0.2](https://github.com/dovecoteescapee/ByeDPIAndroid/releases/tag/1.0.2) you can specify hosts using Command line editor. For example:

`--hosts ":host1.com host2.com host3.com" --split 1`

[Documentation](https://github.com/hufrea/byedpi/blob/main/readme.txt)

**Comment by dovecoteescapee** [comment]
Отмечу, что имя файла в качестве аргумента сейчас не поддерживается. Точнее, оно корректно обработается, но скорее всего Android откажет в правах.

**Comment by celomu** [comment]
лучше скажите и покажите пример как сделать черный спислк в коммандлайн
у меня вивальди перестал синхронизироваться
