### ISSUE TITLE
Аналог конфига goodbyedpi

### ISSUE THREAD

**Issue by 7AllenWalker7** [dovecoteescapee/ByeDPIAndroid#111]
### What problem does your proposal solve? / Какую проблему решает ваше предложение?

--auto-ttl помогает открывать заблокированные сайты (рутрекер рутор анилибрия)
Подскажите если ли  аналогичная команда в byedpi для использования на андроиде.

### Describe the solution you'd like / Опишите решение, которое вы предлагаете

Весь конфиг goodbyedpi, Ютуб и указанные выше сайты работают в виндовс.
-f 2 -e 2 --wrong-chksum --reverse-frag --max-payload -q --auto-ttl

Описание параметра с оффсайта
--auto-ttl    [a1-a2-m]  activate Fake Request Mode, automatically detect TTL and decrease
                          it based on a distance. If the distance is shorter than a2, TTL is decreased
                          by a2. If it's longer, (a1; a2) scale is used with the distance as a weight.
                          If the resulting TTL is more than m(ax), set it to m.
                          Default (if set): --auto-ttl 1-4-10. Also sets --min-ttl 3.

### Describe alternatives you've considered / Опишите альтернативные варианты, которые вы рассматривали

Альтернативные варианты это ВПН, хотелось бы иметь способ без потери скорости или подмены местоположения.

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] I have verified that this feature does not already exist / Я убедился(ась), что эта функция еще не существует

**Comment by dovecoteescapee** [comment]
В чём заключается ваше предложение? Если это вопрос по настройке, пожалуйста, задавайте его в разделе [дискуссий](https://github.com/dovecoteescapee/ByeDPIAndroid/discussions)
