### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Shidapu** [dovecoteescapee/ByeDPIAndroid#112]
### What problem does your proposal solve? / Какую проблему решает ваше предложение?

Autostart on boot, and auto start proxy mode in app.

### Describe the solution you'd like / Опишите решение, которое вы предлагаете

Please add Autostart on boot in settings. 

### Describe alternatives you've considered / Опишите альтернативные варианты, которые вы рассматривали

No alternatives available.

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] I have verified that this feature does not already exist / Я убедился(ась), что эта функция еще не существует

**Comment by dovecoteescapee** [comment]
Дубликат #2

**Comment by Shidapu** [comment]
Hmm, im guessing thats a no, considering that this topic got closed without an answer.

**Comment by dovecoteescapee** [comment]
Sorry, this is a duplicate of the issue #2 (it's in Russian)

**Comment by Shidapu** [comment]
> Sorry, this is a duplicate of the issue #2 (it's in Russian)

Ah Okey, thanks for clarifying!
