### ISSUE TITLE
App banner doesn't show up in Android TV launcher and app list (even in settings, at least on Xiaomi TV)

### ISSUE THREAD

**Issue by kastentop2005** [dovecoteescapee/ByeDPIAndroid#13]
Does this issue persist on Google TV as well? Can someone tell?

**Comment by idx1337** [comment]
Баннер действительно не отображается и в целом на sony android tv не заработало. При включении приложения контакт между тв и интернетом разрывается, не грузит ничего.

**Comment by denmorgenshtern** [comment]
what settings did you use to work on Android TV? it doesn't help at all with YouTube, although similar projects (GoodbyeDPI / SpoofDPI) are working fine on their platforms (Windows/macOS).

**Comment by unit66** [comment]
@dovecoteescapee доп инфа по проблеме. Возможно чем-то окажется полезной.
ТВ-стик актуальный Google Chromecast HD(актуальная Android TV OS 12).
Не работает YouTube.

Конфиг следующий:

_Desync Method: Fake
Split position: 1
TTL of fake packets: 7
TLS record split position: 1
Split TLS at SNI: true
(остальное в дефолтных параметрах)_

Что странно:
- с этим конфигом **ЗАРАБОТАЛО** приложение **SmartTube** на ТВ-стике(без ByeDPIAndroid НЕ работало).
- с этим конфигом **ЗАРАБОТАЛО** приложение **YouTube** на телефоне Google Pixel 8Pro(без ByeDPIAndroid НЕ работал). Актуальная Android 14, оба девайса в одной и той-же вай-фай сети.

**Comment by hooddy** [comment]
Так и не появился в лончере на ящике. Да и как выше пишут не работает.

**Comment by dovecoteescapee** [comment]
В данный момент приложение не поддерживает Android TV. Я займусь его поддержкой позже.

**Comment by dmitrystarosta** [comment]
> Так и не появился в лончере на ящике. Да и как выше пишут не работает.

Если установить ByeDPI на Андроид ТВ, то найти приложение можно в Настройки > Приложения > Все приложения > Системные приложения .. далее по алфавиту найти и запустить. Пока только так на моём Sony. 
Замечу, что Ютуб не пашет даже с включенным ВПН (WireGuard + частный зарубежный vps). Но при включенном ВПН и включенном ByeDPI работает отлично (настройки приложения по умолчанию).
Но ByeDPI постоянно отключается после некоторого времени не пользования Ютуб и снова приходится лезть в дебри настроек телевизора, чтобы включить байдипиай.

Это я так. Просто опытом поделился )

**Comment by AvrilL161** [comment]
У меня на андроид тв, приложение работает следующим образом (работают все версии, настройки по умолчанию).
Иконки установленного приложения у меня не появляется, поэтому я использую cx file explorer.
1. Запускаю через cx file explorer, ByeDPIAndroid, но не подключаюсь.
2. Сворачиваю ByeDPIAndroid, и запускаю приложение YouTube, теперь надо дождаться звука запуска приложения или частичной прогрузки интерфейса (обычно 10-30 сек).
3. Возвращаюсь в ByeDPIAndroid, жму подключится, и возвращаюсь в YouTube. И он становится полностью рабочим.

Перед проведением этих манипуляций лучше перезагрузить ОС.

Проверенно на Mi Stick 4k, и на телевизоре Xiaomi TV A Pro 75.

На телефонах работает без танцев с бубном.
