### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by lao-mang** [dovecoteescapee/ByeDPIAndroid#141]
### Describe the bug / Описание ошибки

Просто перестало работать на ростелекоме и на билайне. 

### To Reproduce / Как воспроизвести

Просто включить

### Expected behavior / Ожидаемое поведение

Сеть работает / но не работает

### Environment / Окружение

Sony xperia h4213.   Android 9

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] This is not a question, feature request, or general feedback / Это не вопрос, предложение новой функциональности или общий отзыв

**Comment by TaradinAS** [comment]
Та же проблема на ANE-LX1 Android 9 kernel 4.9.148. Пробовал разные параметры командной строки (TTL 3/4, fake, disorder, split 1+s) и совсем без них, разные DNS (Cloudfare, Google, Quad9).

**Comment by lufog** [comment]
У меня тоже фэйки перестали работать, работающий, на компе с Linux, конфиг, не работает на Android, в той же сети. Возможно проблема пофикшена в https://github.com/hufrea/byedpi/pull/115.

**Comment by TaradinAS** [comment]
Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`

**Comment by GennadijK1987** [comment]
> Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`

Подскажите пожалуйста, а где именно эти параметры нужно прописывать ?
В свойствах ярлыка ?

**Comment by koreshforever** [comment]
На МТС эффективнее всего работает по листу 
![IMG_20240912_083842](https://github.com/user-attachments/assets/00666208-9c6c-44ad-96e9-723ecb2e0e22)

**Comment by TaradinAS** [comment]
> > Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`
> 
> Подскажите пожалуйста, а где именно эти параметры нужно прописывать ? В свойствах ярлыка ?

Переходите в настройки через шестерёнку. В них внизу включаете ползунок **Use command line settings** и вам станет доступно меню **Command line editor**. Переходите в него и вписываете аргументы по документации отсюда https://github.com/hufrea/byedpi. Важно: каждый аргумент начинается с двойной `--`, если это слово, либо с одинарной `-`, если это буква (краткая форма записи); аргументы разделяются пробелами; после аргумента ставится его значение (если его можно указать); аргументы читаются программой слева направо.

Также, перед `--fake` (`-f`) иногда требуется ставить `--split` (`-s`) или `--disorder` (`-d`) для работы на домашнем интернете. Но это уже задача для вас - подобрать верную конфигурацию.

**Comment by GennadijK1987** [comment]
> > > Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`
> > 
> > 
> > Подскажите пожалуйста, а где именно эти параметры нужно прописывать ? В свойствах ярлыка ?
> 
> Переходите в настройки через шестерёнку. В них внизу включаете ползунок **Use command line settings** и вам станет доступно меню **Command line editor**. Переходите в него и вписываете аргументы по документации отсюда https://github.com/hufrea/byedpi. Важно: каждый аргумент начинается с двойной `--`, если это слово, либо с одинарной `-`, если это буква (краткая форма записи); аргументы разделяются пробелами; после аргумента ставится его значение (если его можно указать); аргументы читаются программой слева направо.
> 
> Также, перед `--fake` (`-f`) иногда требуется ставить `--split` (`-s`) или `--disorder` (`-d`) для работы на домашнем интернете. Но это уже задача для вас - подобрать верную конфигурацию.

Спасибо большое за подробные пояснения :)
Пригодится для андройд устройств , а я думал что именно для домашнего интернета на ПК этот способ подходит, а оказывается что нет...судя по описанию.

**Comment by LexMrack** [comment]
> На МТС эффективнее всего работает по листу ![IMG_20240912_083842](https://private-user-images.githubusercontent.com/75268494/366739096-00666208-9c6c-44ad-96e9-723ecb2e0e22.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjM0MDIsIm5iZiI6MTcyNjE2MzEwMiwicGF0aCI6Ii83NTI2ODQ5NC8zNjY3MzkwOTYtMDA2NjYyMDgtOWM2Yy00NGFkLTk2ZTktNzIzZWNiMmUwZTIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3NDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYWY5ZjQ4NGM5MDA5YWY4M2JiYTc0MTE4ZDIxYTA3NzU2ZWZmZWI0ZjIwNWY3NmE1ZTllMjlkMWQ4ZGI1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0YlV8ItdFXEKfAvEsqac0I8XUJhffYXMiPRZlahd5I)

На Ростелекоме тоже сработало. Правда -H ggjhя я не писал

**Comment by GennadijK1987** [comment]
> > > Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`
> > 
> > 
> > Подскажите пожалуйста, а где именно эти параметры нужно прописывать ? В свойствах ярлыка ?
> 
> Переходите в настройки через шестерёнку. В них внизу включаете ползунок **Use command line settings** и вам станет доступно меню **Command line editor**. Переходите в него и вписываете аргументы по документации отсюда https://github.com/hufrea/byedpi. Важно: каждый аргумент начинается с двойной `--`, если это слово, либо с одинарной `-`, если это буква (краткая форма записи); аргументы разделяются пробелами; после аргумента ставится его значение (если его можно указать); аргументы читаются программой слева направо.
> 
> Также, перед `--fake` (`-f`) иногда требуется ставить `--split` (`-s`) или `--disorder` (`-d`) для работы на домашнем интернете. Но это уже задача для вас - подобрать верную конфигурацию.

Попробовал вот так , но при запуске пишет failed vpn . Dns 8.8.8.8
![Screenshot_2024-09-12-23-59-50-73](https://github.com/user-attachments/assets/c9b237b4-1b08-4ef3-9ce0-6dc23a1ef250)

**Comment by koreshforever** [comment]
> > > Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`
> > 
> > 
> > Подскажите пожалуйста, а где именно эти параметры нужно прописывать ? В свойствах ярлыка ?
> 
> Переходите в настройки через шестерёнку. В них внизу включаете ползунок **Use command line settings** и вам станет доступно меню **Command line editor**. Переходите в него и вписываете аргументы по документации отсюда https://github.com/hufrea/byedpi. Важно: каждый аргумент начинается с двойной `--`, если это слово, либо с одинарной `-`, если это буква (краткая форма записи); аргументы разделяются пробелами; после аргумента ставится его значение (если его можно указать); аргументы читаются программой слева направо.
> 
> Также, перед `--fake` (`-f`) иногда требуется ставить `--split` (`-s`) или `--disorder` (`-d`) для работы на домашнем интернете. Но это уже задача для вас - подобрать верную конфигурацию.

Я думаю это излишнее. У людей всё равно будет куча вопросов. Надо курить руководства по использованию командных оболочек. 

Почему одинарное и двойное тире? Да потому что так исторически сложилось. Любая программа воспринимает последовательности разделённые пробелами как аргументы.

**Comment by Jonerys** [comment]
МТС, Южный Урал, с сегодняшнего дня перестало работать на стоковых настройках. Работает с включенным Split TLS Record, но начинаются проблемы с сертификатами на некоторых сайтах. Например, если Archiveofourown открывается, Kemono уже нет.

**Comment by MrFrozen331** [comment]
> > > Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`
> > 
> > 
> > Подскажите пожалуйста, а где именно эти параметры нужно прописывать ? В свойствах ярлыка ?
> 
> Переходите в настройки через шестерёнку. В них внизу включаете ползунок **Use command line settings** и вам станет доступно меню **Command line editor**. Переходите в него и вписываете аргументы по документации отсюда https://github.com/hufrea/byedpi. Важно: каждый аргумент начинается с двойной `--`, если это слово, либо с одинарной `-`, если это буква (краткая форма записи); аргументы разделяются пробелами; после аргумента ставится его значение (если его можно указать); аргументы читаются программой слева направо.
> 
> Также, перед `--fake` (`-f`) иногда требуется ставить `--split` (`-s`) или `--disorder` (`-d`) для работы на домашнем интернете. Но это уже задача для вас - подобрать верную конфигурацию.

Подскажите, а почему документация в https://github.com/hufrea/byedpi , а не https://github.com/dovecoteescapee/ByeDPIAndroid ?
И что за детали надо пробовать указывать после аргумента -s и -d , если домашний интернет? Подскажите, пожалуйста, а то понимаю от слова нисколько практически. И ещё, у меня ютруба работает только в GBox или Gspace вирт машине, на аппарате Huawei с ихней ОС Harmony 3.1.0, т.e там и без ТСПУ фризы лаги и прочее. Как byedpi может конфликтовать вообще с машинами Gbox и Gspace, и как с этим бороться?

**Comment by lolyinseo** [comment]
> > > > Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`
> > > 
> > > 
> > > Подскажите пожалуйста, а где именно эти параметры нужно прописывать ? В свойствах ярлыка ?
> > 
> > 
> > Переходите в настройки через шестерёнку. В них внизу включаете ползунок **Use command line settings** и вам станет доступно меню **Command line editor**. Переходите в него и вписываете аргументы по документации отсюда https://github.com/hufrea/byedpi. Важно: каждый аргумент начинается с двойной `--`, если это слово, либо с одинарной `-`, если это буква (краткая форма записи); аргументы разделяются пробелами; после аргумента ставится его значение (если его можно указать); аргументы читаются программой слева направо.
> > Также, перед `--fake` (`-f`) иногда требуется ставить `--split` (`-s`) или `--disorder` (`-d`) для работы на домашнем интернете. Но это уже задача для вас - подобрать верную конфигурацию.
> 
> Подскажите, а почему документация в https://github.com/hufrea/byedpi , а не https://github.com/dovecoteescapee/ByeDPIAndroid ? И что за детали надо пробовать указывать после аргумента -s и -d , если домашний интернет? Подскажите, пожалуйста, а то понимаю от слова нисколько практически. И ещё, у меня ютруба работает только в GBox или Gspace вирт машине, на аппарате Huawei с ихней ОС Harmony 3.1.0, т.e там и без ТСПУ фризы лаги и прочее. Как byedpi может конфликтовать вообще с машинами Gbox и Gspace, и как с этим бороться?

1. ByeDPIAndroid  это обертка над byedpi
2. На Huawei прекрасно работает youtube revanced

**Comment by MrFrozen331** [comment]
> > > > > Заработало для каждого DNS выше на домашнем интернете с аргументами: `-f 1+s -t 3`
> > > > 
> > > > 
> > > > Подскажите пожалуйста, а где именно эти параметры нужно прописывать ? В свойствах ярлыка ?
> > > 
> > > 
> > > Переходите в настройки через шестерёнку. В них внизу включаете ползунок **Use command line settings** и вам станет доступно меню **Command line editor**. Переходите в него и вписываете аргументы по документации отсюда https://github.com/hufrea/byedpi. Важно: каждый аргумент начинается с двойной `--`, если это слово, либо с одинарной `-`, если это буква (краткая форма записи); аргументы разделяются пробелами; после аргумента ставится его значение (если его можно указать); аргументы читаются программой слева направо.
> > > Также, перед `--fake` (`-f`) иногда требуется ставить `--split` (`-s`) или `--disorder` (`-d`) для работы на домашнем интернете. Но это уже задача для вас - подобрать верную конфигурацию.
> > 
> > 
> > Подскажите, а почему документация в https://github.com/hufrea/byedpi , а не https://github.com/dovecoteescapee/ByeDPIAndroid ? И что за детали надо пробовать указывать после аргумента -s и -d , если домашний интернет? Подскажите, пожалуйста, а то понимаю от слова нисколько практически. И ещё, у меня ютруба работает только в GBox или Gspace вирт машине, на аппарате Huawei с ихней ОС Harmony 3.1.0, т.e там и без ТСПУ фризы лаги и прочее. Как byedpi может конфликтовать вообще с машинами Gbox и Gspace, и как с этим бороться?
> 
> 1. ByeDPIAndroid  это обертка над byedpi
> 2. На Huawei прекрасно работает youtube revanced

1. Понятно.
2. Ммм, решил специально установить все заново, чтобы показать, что НЕ работает microG логин от revanced
![Screenshot_20240914_111357_app revanced android gms](https://github.com/user-attachments/assets/299ab1f1-3178-4c9c-b40c-6d71d2f04e13)

**Comment by vetas63** [comment]
Всем привет, на планшете Андройд работает, на Гугл ТВ перестал работать, при загрузке Ютуба просто пустой экран без каких либо ошибок и изображений, что может быть и как это исправить, скажите пожалуйста.

**Comment by MrFrozen331** [comment]
> ?
> 
> 1. ByeDPIAndroid  это обертка над byedpi
> 2. На Huawei прекрасно работает youtube revanced

Вот установленное из revanced, есть сам ютуб и microG
![Screenshot_20240914_114013_com revanced net revancedmanager](https://github.com/user-attachments/assets/4620a90b-250c-400a-9efd-851cbce9d1d1)

Само ПО revanced Yotube работает 
![Screenshot_20240914_113010_app revanced android youtube](https://github.com/user-attachments/assets/639d9f44-c4c0-496f-a6fb-2d7c41c5de43)

Логин не работает, скрин выше. Смысла в нерабочем приложении нет, если только не известно, как ссылку на видео/плейлист туда скинуть, я согласен даже на такие костыли. Но возможности такой в приложении нет.

**Comment by lolyinseo** [comment]
> Вот установленное из revanced, есть сам ютуб и microG

https://4pda.to/forum/index.php?showtopic=1050118&st=43000#entry129271360

А вместо этого ByeDPIAndroid лучше использовать его форк https://github.com/romanvht/ByeDPIAndroid, в котором можно настроить фильтр приложений. В самом ByeDPIAndroid  используйте "параметры командной строки" - возможно нужно будет подобрать под оператора

**Comment by MrFrozen331** [comment]
> > Вот установленное из revanced, есть сам ютуб и microG
> 
> https://4pda.to/forum/index.php?showtopic=1050118&st=43000#entry129271360
> 
> А вместо этого ByeDPIAndroid лучше использовать его форк https://github.com/romanvht/ByeDPIAndroid, в котором можно настроить фильтр приложений. В самом ByeDPIAndroid используйте "параметры командной строки" - возможно нужно будет подобрать под оператора

Благодарю, заработало всё! А подскажите, почему byedpi лучше тот форк использовать (работает и с этим, пару минут вот только проверял, нужно подольше конечно), с чем это связано?

**Comment by lolyinseo** [comment]
> > > Вот установленное из revanced, есть сам ютуб и microG
> > 
> > 
> > https://4pda.to/forum/index.php?showtopic=1050118&st=43000#entry129271360
> > А вместо этого ByeDPIAndroid лучше использовать его форк https://github.com/romanvht/ByeDPIAndroid, в котором можно настроить фильтр приложений. В самом ByeDPIAndroid используйте "параметры командной строки" - возможно нужно будет подобрать под оператора
> 
> Благодарю, заработало всё! А подскажите, почему byedpi лучше тот форк использовать (работает и с этим, пару минут вот только проверял, нужно подольше конечно), с чем это связано?

Авто этого похоже тихонько забил на проект. Заворачивать ВЕСЬ трафик на vpn нельзя, во 1 это дикий оверхед, во 2 это ломает работу некоторых приложений, так как ломает tls. Правильно - установить форк и выбрать напр только revanced

**Comment by MrFrozen331** [comment]
> > > > Вот установленное из revanced, есть сам ютуб и microG
> > > 
> > > 
> > > https://4pda.to/forum/index.php?showtopic=1050118&st=43000#entry129271360
> > > А вместо этого ByeDPIAndroid лучше использовать его форк https://github.com/romanvht/ByeDPIAndroid, в котором можно настроить фильтр приложений. В самом ByeDPIAndroid используйте "параметры командной строки" - возможно нужно будет подобрать под оператора
> > 
> > 
> > Благодарю, заработало всё! А подскажите, почему byedpi лучше тот форк использовать (работает и с этим, пару минут вот только проверял, нужно подольше конечно), с чем это связано?
> 
> Авто этого похоже тихонько забил на проект. Заворачивать ВЕСЬ трафик на vpn нельзя, во 1 это дикий оверхед, во 2 это ломает работу некоторых приложений, так как ломает tls. Правильно - установить форк и выбрать напр только revanced

Спасибо, буду посмотреть что устанавливать из обхода тут уже сам, и параметры подбирать. Главное, что у меня теперь -1 проблема из цепочки проблем (где непонятно что не работает), спасибо большое

**Comment by lao-mang** [comment]
уже заработало.

**Comment by Damienbro** [comment]
Почитал ваше обсуждение, пробовал ваши варианты прописать в командной строке для домашнего МГТС, ничего не помогло. Скопировал вот этот с других настроек dpi — заработало всё, до этого не грузились шортсы. Спасибо за мысль, как это можно сделать.
![Screenshot_20240915_214409_ByeByeDPI](https://github.com/user-attachments/assets/d033d60c-9ee0-4c48-a11c-53d359c57967)

**Comment by GennadijK1987** [comment]
А нужны ли аргументы , если я пользуюсь byidpi на Андроиде и если да, то какие нужны ? Провайдер Ростелеком.
