### ISSUE TITLE
Не работает после запуска приложение Youtube на Android TV

### ISSUE THREAD

**Issue by almirus** [dovecoteescapee/ByeDPIAndroid#15]
Приветствую. Установил на Nvidia Shield, после включения при запуске Youtube получаю ошибку "Нет сети", при этом остальные приложения работают. Поигрался с галочками - ошибка таж.

**Comment by idx1337** [comment]
Аналогично, не работают любые приложения требующие соединения с интернетом

**Comment by olegosipenko** [comment]
> Аналогично, не работают любые приложения требующие соединения с интернетом

Не подтверждаю. Не работает Youtube, Youtube Kids, остальные приложения работают. Проверено - Start, VK Video, XVideos, Кинопоиск

**Comment by kelr0nd** [comment]
Приложение YouTube на AndroidTV не работает, пишет, что нет доступа к сети

**Comment by dovecoteescapee** [comment]
duplicate #13
