### ISSUE TITLE
Не работает Quora /do not work Quora

### ISSUE THREAD

**Issue by MrFrozen331** [dovecoteescapee/ByeDPIAndroid#161]
### Describe the bug / Описание ошибки

No connection только на сайте Quora и приложении Quora при включенном ByeByeDPI форка от romanvht (самый стабильный имхо), фильтров нет. С любым ВПН загружается, хоть и медленно первая итерация, то есть с чистым кэшем до момента входа; Facebook, YouTube, всё работает при кастомных настройках (иногда меняю, когда ютуб лагает, ничего не меняется - на Quora не зайти) прекрасно. С другими форками тоже Quora не открывается. 
![Screenshot_20241002_164828_com gbox android](https://github.com/user-attachments/assets/af195335-3bac-4eea-8346-6f823121442a)

### To Reproduce / Как воспроизвести

1. Go to 'https://www.quora.com' or app 'Quora'
2. Click on something,
3. Scroll down to something 
4. See error 'No internet connection. Please connect and try again'

### Expected behavior / Ожидаемое поведение

Работа сайта Quora

### Environment / Окружение

**Smartphone / Смартфон:**
- Device: [Huawei MatePad 11 (huawei matepad dbr-w09)]
- Android version: [-; Harmony OS 3.1.0]
- ByeDPI version: [v1.3.5 by romanhvt]
![Screenshot_20241002_165239_dev imranr obtainium fdroid](https://github.com/user-attachments/assets/ab0d138f-f4b5-4e0e-9dd0-bda276b8e9e8)

### Additional context / Дополнительная информация

Все заблокированное, замедленное, кроме Quora, работает.

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] This is not a question, feature request, or general feedback / Это не вопрос, предложение новой функциональности или общий отзыв

**Comment by romanvht** [comment]
1. Вы отправили скриншот из другого репозитория, он не принадлежит текущему и автор (dovecoteescapee) не несет ответственности за его работоспособность

**Comment by romanvht** [comment]
2. 
![Screenshot_20241004-024848](https://github.com/user-attachments/assets/3d3279fc-bcd5-4909-a704-9f107a557dcb)

А по поводу сайта, проверил на нескольких устройствах, с разными настройками. Все работает. Скорее всего виной всему провайдер

**Comment by MrFrozen331** [comment]
> 1. Вы отправили скриншот из другого репозитория, он не принадлежит текущему и автор (dovecoteescapee) не несет ответственности за его работоспособность

Нет кнопки issues в вашем репозитарии, поэтому тут ТТ
![Screenshot_20241004_034746_com gbox android](https://github.com/user-attachments/assets/104cac59-8735-466c-968a-c2ffa99e5785)
![Screenshot_20241004_034733_com gbox android](https://github.com/user-attachments/assets/1dcb207b-13de-452c-b895-e5beae814446)


> 
> А по поводу сайта, проверил на нескольких устройствах, с разными настройками. Все работает. Скорее всего виной всему провайдер

Это понятно, хотя я и на устройство само думаю уже. На других всё нормально сейчас, а этот Huawei перестал нормально открывать Facebook и ещё некоторые сайты, помимо quora. Я вот думаю, не дело ли в уже установленной куче VPN/proxy/др.методах на устройстве
![Screenshot_20241004_033938_com huawei android launcher](https://github.com/user-attachments/assets/e8364d28-a603-43f3-82bd-e41d2d196812)
![Screenshot_20241004_034230_org mozilla firefox](https://github.com/user-attachments/assets/0dde3ede-ab47-43b5-bc81-78a3148ed57f)
![Screenshot_20241004_035909_com android settings](https://github.com/user-attachments/assets/c0eb0aaf-b419-40dc-a6f5-9c1a1c800c44)
![Screenshot_20241004_040757_com gspace android](https://github.com/user-attachments/assets/3acfa232-3c80-4dcc-8314-d28824627470)

**Comment by MrFrozen331** [comment]
Вот данные по отладке с ютуб ревансед если нужно
{"cplatform":"tablet","cff":"LARGE_FORM_FACTOR","c":"android","cplayer":"PLATYPUS","cmodel":"DBR-W09","cos":"Android","soc":"QTI:SM8250","cver":"19.16.39","cbrand":"HUAWEI","cbr":"app.revanced.android.youtube","csdk":"31","cbrver":"19.16.39","cosver":"12.HUAWEIDBR-W09.103.1.0.212C10","videoid":"d6BAPHtrMH0","cpn":"w9itUqCtLnOuB66T","fmt":"N\/A","afmt":"140:CggKA2RyYxIBMQ mp4a","bh":23984,"conn":3,"volume":6,"loudness":"-0.610","bat":"0.560:0","df":"0\/188","time":"2024-10-04T02:13:36.828Z","glmode":"RECTANGULAR_2D","drm":"","mtext":"","error":"No errors","logged_in":"1","e":"23888717,23966208,24004644,24077241,24078649,24104894,24117491,24132305,24166867,24181174,24186126,24230811,24232551,24241378,24378826,24397985,24407176,24458684,24475157,24522874,24542367,24548465,24548629,24556101,24580392,24585134,24585737,39325413,39325841,51009781,51010008,51017346,51020570,51021185,51024556,51025415,51030101,51037344,51037353,51038803,51041512,51043775,51046127,51048236,51050361,51053689,51054999,51057846,51057853,51064835,51067700,51068313,51080128,51081684,51095478,51111738,51115164,51115184,51124104,51125020,51129105,51132530,51132535,51137671,51141472,51152050,51157411,51157838,51157919,51158514,51160339,51160545,51162170,51165467,51169118,51172966,51176511,51177818,51178316,51178333,51178348,51178351,51178982,51179435,51179748,51179884,51180609,51183211,51183909,51186367,51189369,51190652,51190722,51195231,51208302,51212466,51217332,51217334,51217504,51221011,51221150,51223962,51224135,51225966,51226535,51226860,51227037,51227776,51228350,51228690,51228769,51228776,51228785,51228800,51228805,51228812,51230241,51230478,51230710,51231220,51231814,51237842,51239093,51241028,51242448,51243940,51246283,51246301,51248255,51248734,51251836,51255676,51255680,51255708,51255743,51256084,51257108,51257900,51257909,51257918,51258066,51259133,51260456,51260636,51264983,51265339,51265356,51265367,51265785,51266454,51267568,51269739,51272458,51272491,51272500,51272513,51272532,51272576,51272589,51275148,51275163,51275168,51275185,51275198,51275785,51276557,51276565,51276641,51277293,51280514,51281227,51282064,51282075,51282080,51285417,51287196,51287500,51287512,51287513,51288968,51289922,51289933,51289938,51289956,51289965,51289970,51290097,51290418,51290606,51291888,51292706,51295132,51295408,51296439,51297225,51298830,51299649,51299711,51299724,51299973,51300005,51300012,51300699,51300751,51300760,51301606,51302064,51302358,51302492,51302679,51303667,51303670,51303726,51303790,51304121,51304155,51304276,51304392,51305311,51305496,51305839,51306265,51306543,51307636,51310742,51311289,51311556,51311921,51312505,51313148,51313529"}

**Comment by romanvht** [comment]
Ну, как вариант, снести все неиспользуемые VPN и сбросить все настройки сети, в том числе "Частный DNS". После этого проверить.
Или попробовать создать вторую локальную учётную запись, поставить туда ByeDPI и попробовать

**Comment by MrFrozen331** [comment]
> Ну, как вариант, снести все неиспользуемые VPN и сбросить все настройки сети, в том числе "Частный DNS". После этого проверить. Или попробовать создать вторую локальную учётную запись, поставить туда ByeDPI и попробовать

Кроме powertunel и по shadowsocks (хотя, там надо попробовать настроики покрутить и др. серваки - но мне влом, это долгая история) всё рабочее (ну, с разной скоростью конечно), так что, что именно удалять ещё тот вопрос.. Ладно, я issue закрываю, но ничего не работает, не только в вашем форке: из любопытства ставил снова форк dowecoteescapee, не работает, к сожалению (в obtainium только 1 форк одновременно одного и того же проекта можно установить)
