### ISSUE TITLE
Youtube android app

### ISSUE THREAD

**Issue by VolodyaUrban** [dovecoteescapee/ByeDPIAndroid#20]
Казалось бы, все хорошо, рутрекер открывается, но в приложении ютуба видео 144р
Какие оптимальные настройки для просмотра видео, может я не правильно настроил?

**Comment by Ranger21** [comment]
Причём началось это 01.08.2024. до этого было лучше

**Comment by SergeVDev** [comment]
Я правильно понимаю, что андроидное приложение Ютуба испрользует QUIK, и поможет открывать Ютуб в мобильном Firefox?

**Comment by VolodyaUrban** [comment]
К слову, в хроме тоже не корректно работает утуб

**Comment by johnceena0** [comment]
Дело в том что приложение использует принудительно включенный QUIC и его нельзя отключить в официальном приложении и в YouTube ReVanced, но можно отключить в YouTube ReVanced Extended. У меня эта настройка находится в Settings -> ReVanced Extended -> Miscellaneous -> Disable QUIC protocol. В Settings -> ReVanced Extended -> Miscellaneous -> Spoof client надо еще было отключить переключатель Spoof client, для чего точно - не знаю, но без этого не работает. С таким ютуб клиентом и ByeDPIAndroid в фоне замедление наконец исчезло.

**Comment by SergeVDev** [comment]
> Дело в том что приложение использует принудительно включенный QUIC и его нельзя отключить в официальном приложении и в YouTube ReVanced, но можно отключить в YouTube ReVanced Extended. У меня эта настройка находится в Settings -> ReVanced Extended -> Miscellaneous -> Disable QUIC protocol. В Settings -> ReVanced Extended -> Miscellaneous -> Spoof client надо еще было отключить переключатель Spoof client, для чего точно - не знаю, но без этого не работает. С таким ютуб клиентом и ByeDPIAndroid в фоне замедление наконец исчезло.

Спасибо, буду иметь в виду. А не проще, как я предложил, смотреть Ютуб в мобильном Firefox? По крайней мере, десктопный ФФ не использует QUIK на Ютубе (я подозреваю, это отключено на стороне Ютуба для всех браузеров кроме Хрома, иначе объянить не могу).

**Comment by johnceena0** [comment]
> > Дело в том что приложение использует принудительно включенный QUIC и его нельзя отключить в официальном приложении и в YouTube ReVanced, но можно отключить в YouTube ReVanced Extended. У меня эта настройка находится в Settings -> ReVanced Extended -> Miscellaneous -> Disable QUIC protocol. В Settings -> ReVanced Extended -> Miscellaneous -> Spoof client надо еще было отключить переключатель Spoof client, для чего точно - не знаю, но без этого не работает. С таким ютуб клиентом и ByeDPIAndroid в фоне замедление наконец исчезло.
> 
> Спасибо, буду иметь в виду. А не проще, как я предложил, смотреть Ютуб в мобильном Firefox? По крайней мере, десктопный ФФ не использует QUIK на Ютубе (я подозреваю, это отключено на стороне Ютуба для всех браузеров кроме Хрома, иначе объянить не могу).
> 
> Кстати, у меня в мобильном ФФ тормозов больше нет, думаю, из-за этого.

Тоже вариант, просто у меня не самый мощный телефон и сам интерфейс ютуба в браузере подлагивает, мне лично некомфортно, поэтому и нашел такой способ.

**Comment by icynstant** [comment]
> Дело в том что приложение использует принудительно включенный QUIC и его нельзя отключить в официальном приложении и в YouTube ReVanced, но можно отключить в YouTube ReVanced Extended. У меня эта настройка находится в Settings -> ReVanced Extended -> Miscellaneous -> Disable QUIC protocol. В Settings -> ReVanced Extended -> Miscellaneous -> Spoof client надо еще было отключить переключатель Spoof client, для чего точно - не знаю, но без этого не работает. С таким ютуб клиентом и ByeDPIAndroid в фоне замедление наконец исчезло.

Функция Spoof client использовалась чтобы обойти блокировку модов для ютуба, ютуб несколько месяцев назад начал блокировать RVX и тп потому что хочет получать больше денег с рекламы

**Comment by johnceena0** [comment]
> > В Settings -> ReVanced Extended -> Miscellaneous -> Spoof client надо еще было отключить переключатель Spoof client, для чего точно - не знаю, но без этого не работает.
> 
> Функция Spoof client использовалась чтобы обойти блокировку модов для ютуба, гугл несколько месяцев назад начал блокировать RVX и тп потому что хочет получать больше денег с рекламы

Во, хорошее замечание, но у меня почему-то нет проблем с клиентом при выключении этой функции, + с ней включается замедление

**Comment by krlvm** [comment]
> А не проще, как я предложил, смотреть Ютуб в мобильном Firefox?

Используйте [NewPipe](https://github.com/TeamNewPipe/NewPipe)

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждения, не относящиеся к разработке, в discussions https://github.com/dovecoteescapee/ByeDPIAndroid/discussions/62
