### ISSUE TITLE
Просто не работает.

### ISSUE THREAD

**Issue by lynrayy** [dovecoteescapee/ByeDPIAndroid#21]
Для проверки работы беру порнушные сайты e621.net и furaffinity.net, которые 100% заблокированы в россии

Запускаю приложение, даю ему доступ как впн приложению в андроиде
![image](https://github.com/user-attachments/assets/fbecc2a6-1133-42bd-8d42-6c7786fc051a)

Оно запущено
![image](https://github.com/user-attachments/assets/f428774e-d70e-4bcf-9329-d5a3fafdb669)

Однако переход на запрещённый сайт не удаётся - открывается заглушка оператора

![image](https://github.com/user-attachments/assets/b94685cc-aeaf-4754-9212-bc4ed588e304)

**Comment by lynrayy** [comment]
В том числе в тви и инсте не работает

**Comment by Ranger21** [comment]
По моему это работало, но перестало работать

**Comment by dovecoteescapee** [comment]
В зависимости от оператора могут работать различные настройки. Для обсуждения настроек создал https://github.com/dovecoteescapee/ByeDPIAndroid/discussions.
