### ISSUE TITLE
Работает, но как бы не работает.

### ISSUE THREAD

**Issue by Lisyachiy-y** [dovecoteescapee/ByeDPIAndroid#22]
На Ютубе появились аватарки и возможность просмотра картинок в сообществе, но вот видео точно также тормозят.

**Comment by vC0sul** [comment]
репозиторий использует старую версию bye dpi, а возможно есть проблема с подменой TTL

**Comment by Gor500** [comment]
Ждем гайда от умельцев, фикс dns на 1.1.1.1 не помог мне...

**Comment by trueTrueman** [comment]
То же самое, что у автора первого сообщения, ну и плюс еще заблокированные сайты в браузере стали открываться, но видео на Ютубе всё так же виснет.

**Comment by dovecoteescapee** [comment]
Блокировка домена с аватарками и замедление видео это две отдельные блокировки. Предлагаю перенести подбор подходящих настроек вы можете в discussions https://github.com/dovecoteescapee/ByeDPIAndroid/discussions/62.
