### ISSUE TITLE
Youtube в России

### ISSUE THREAD

**Issue by Bully1235** [dovecoteescapee/ByeDPIAndroid#23]
Блокировка от провайдера походу зависит, МТС что-то очень жестко заблокировали, вроде работает нужно в desync method поставить split и заходить через киви браузер, в нем нужно отключить флаги QUIC и Kyber как в обычном хроме chrome://flags.

**Comment by trueTrueman** [comment]
У меня на Ютубе заработали аватарки и картинки в постах сообщества (ну и плюс в браузере стали открываться заблокированные сайты), но против замедления видео не помогло, к сожалению. Параметры из сообщения выше тоже не помогли.

**Comment by 0k0r0k** [comment]
> У меня на Android работает со следующими параметрами: DNS: 9.9.9.9 Listen address: 127.0.0.1 Maximum number of connection: 512 Buffer size: 16384 Default TTL: 0 No domain: false Desync only HTTPS and TLS: false Desins method: Fake Split at host: true TTL of fake packets: 7 SNI of fake packet: [www.iana.org](http://www.iana.org) OOB Data: a Host mixed case: true Domain mixed case: true Host remove spaces: true Split TLS record: true TLS record split position: 1 Split TLS record at SNI: true.
> 
> Иногда подвисает на несколько секунд, но надо подождать и поток восстанавливается.

Попробовал ваш конфиг, первое время как вы и говорили: долго грузится, потом идет просмотр. После нескольких секунд видео 1080р60 начинаются жесткие тормоза. как-будто бы не работает

**Comment by Un-ka** [comment]
> > У меня на Android работает со следующими параметрами: DNS: 9.9.9.9 Listen address: 127.0.0.1 Maximum number of connection: 512 Buffer size: 16384 Default TTL: 0 No domain: false Desync only HTTPS and TLS: false Desins method: Fake Split at host: true TTL of fake packets: 7 SNI of fake packet: [www.iana.org](http://www.iana.org) OOB Data: a Host mixed case: true Domain mixed case: true Host remove spaces: true Split TLS record: true TLS record split position: 1 Split TLS record at SNI: true.
> > Иногда подвисает на несколько секунд, но надо подождать и поток восстанавливается.
> 
> Попробовал ваш конфиг, первое время как вы и говорили: долго грузится, потом идет просмотр. После нескольких секунд видео 1080р60 начинаются жесткие тормоза. как-будто бы не работает

Я проверял упомянутый конфиг, запустив byeDPI  и выполнив в termiux команду `curl --connect-to ::speedtest.selectel.ru https://manifest.googlevideo.com/100MB -k -o/dev/null` взятую из статьи на Хабре https://habr.com/ru/articles/832678/
Её вывод был следующим:
`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL/3.2.1: error:0A00041A:SSL routines::tlsv1 alert decode error`
Также с такими настройками у меня перестало работать TLS Handshake "Этот сайт не может обеспечить безопасное соединение Сайт stackoverflow.com отправил недействительный ответ.
ERR_SSL_PROTOCOL_ERROR"

На revanced даже без средств обхода аудиодорожка подгружается и воспроизводится.

**Comment by gtb86tbl** [comment]
Даже не устанавливается. Приставка UGOOS AM8PRO, андроид 11. Скачивал последний релиз отсюда.
Что может быть?

**Comment by Un-ka** [comment]
> Не устанавливается. Приставка UGOOS AM8PRO, андроид 11. Скачивал последний релиз отсюда. Что может быть?

Лучше создайте отдельный issue с указанием не только модели устройства и версии операционной системы android, но и архитектуры. Не забудьте упомянуть было ли свободное место и устанавливались ли приложения раньше.

**Comment by RazerStvH** [comment]
Для каждой ситуации нужны свои настройки. Тут в общем смысле цель такая: нужно сдеть так, чтоб обманывающие пакеты уперлись в dpi и дальше не пошли, иначе сайт не заработает. К сожалению гибкость настроек оставляет желать лечшего. Оригинальный byedpi имеет больше возможностей и, соответсвенно работает стабильнее. А этот у меня на одних и тех же настройках то работает, то нет.

В общем тут надо перебирать параметры, тыкая буквально наугад. И следить за реакцией.

**Comment by RazerStvH** [comment]
пробуйте еще эти настройки, у меня пока работает. Все что указано - включено, все что не указано - дефолт после reset:
No domain
Desync only HTTPS and TLS
Desync method Ffke
Split at host
Domain mixed case

**Comment by gtb86tbl** [comment]
> пробуйте еще эти настройки, у меня пока работает. Все что указано - включено, все что не указано - дефолт после сброса: Нет домена Десинхронизация только HTTPS и TLS Метод десинхронизации Ffke Разделение на хосте Домен смешанный случай

Всё сделал по указанным настройкам, результат отрицательный.

**Comment by gtb86tbl** [comment]
> пробуйте еще эти настройки, у меня пока работает. Все что указано - включено, все что не указано - дефолт после сброса: Нет домена Десинхронизация только HTTPS и TLS Метод десинхронизации Ffke Разделение на хосте Домен смешанный случай

Еще добавлю. Я запустил Ютуб на югос ам8 и Тох3, где андроид 11, с помощью powertynell.
А вот на югос ам6, где андроид 9, тунелль не подошел. 
Пытаюсь с dpiandroid решить, не получается пока. Вот и твоя конфигурация настроек не подошла.

**Comment by gtb86tbl** [comment]
А нет ли у Ютуба дополнительных настроек, например с движком поиграться или с прокси?

**Comment by RazerStvH** [comment]
Не имею понятия. Повторюсь, все эти настройки индивидульны. а стабильность работы этой проги оставляет желать лучшего, и дело врядли в самой проге, так всегда с мобильными устройствами. 
На Arch Linux вот эта реализация работает изумительно: https://github.com/hufrea/byedpi

Открываются все сайты, в том числе и ютуб. При этом на десктопе без этого ютуб не работает совсем, даже превью не прогружает. 

И на андройд все работает, но только через мобильный инет. Хотя без софта что на мобильном инете, что через вайфай голяк полный.

С софтом вайфай все равно тупит, но вайфай и до этого всегда мозги ебал, видимо зашумленность большая.

**Comment by RazerStvH** [comment]
Могу посоветовать только кропотливо сидеть и перебирать настроки, в том числе не бояться играть с ttl. 
Ибо наша задача отправить фейковые пакеты до dpi серверов, но не до целевого сервера.

**Comment by denmorgenshtern** [comment]
Народ, пробовал все вышеперечисленные варианты настроек. Ютуб не пашет.

Однако, совершенно точно у моего провайдера отлично пашет [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) и [SpoofDPI](https://github.com/xvzc/SpoofDPI). Оба работают на винде/макос из коробки, никакие настройки не менялись. 

Вопрос - как можно "перенести" их настройки в ByeDPIAndroid? Где вообще их смотреть?

**Comment by Fleapse** [comment]
Заметил, что в браузере с приложением - все начинает нормально работать, но по какой то причине полностью перестает работать сеть в гугловых приложениях (как минимум приложение Ютуба и гуглдиска)
При чем началось это сегодня. Вчера приложения работали без проблем

**Comment by RazerStvH** [comment]
Повторяюсь, настройки этого рпиложения весьма урезаны. Если бы вы "покапались" в настройках GoodbyeDPI и SpoofDPI, то вы это бы поняли. Пренести не получится, только кропотливо сидеть и подбирать.

У меня точно так же работает с переменным успехом. Но зато все сайты разлочились.

По поводу мобильно интернета: вы должны держать в голове, что когда вы выходите в сеть через wi-fi, то топология сети отличается. В частности помимио серверов провайдера, трафик проходит через ваш собственный роутер. Что естественно оказывает влияние. Мне приходится менять значение TTL чтобы пакеты могли доходить до сервера назначения.

**Comment by denmorgenshtern** [comment]
> У меня точно так же работает с переменным успехом. Но зато все сайты разлочились.
какие настройки ставили? Или хотя бы какие крутить-проверять? чужие конфиги пробовал, не прокатило.

**Comment by turikf18** [comment]
Нашёл на Пикабу такое решение, все в дефолт сбрасываем , меняем только Split position на 1 или 2,(подбираем что будет работать) Билайн Мск , так заработало

**Comment by denmorgenshtern** [comment]
> все в дефолт сбрасываем , меняем только Split position на 1 или 2,(подбираем что будет работать) 

о, как будто работает с 1, буфер аж до 50с+ видел, но все равно есть редкие обрывы, иногда буфер заканчивается. А потом поновой до 30-50с может заполниться. Но пока это самое рабочее решение. Спасибо!

**Comment by Rusdenius** [comment]
Ростелеком Сибирь, Split position 1, остальные настройки по дефолту. Работает youtube, twitter, instagram

**Comment by Gor500** [comment]
> Нашёл на Пикабу такое решение, все в дефолт сбрасываем , меняем только Split position на 1 или 2,(подбираем что будет работать) Билайн Мск , так заработало

У меня не сработало (Ростелеком)...

**Comment by eddiezato** [comment]
Как соотнести настройки, например, zapret и в этом приложении. В zapret есть прекрасно работающие для меня стратегии и на win, и на lin. Например, `--dpi-desync=fake,disorder2 --dpi-desync-fooling=md5sig`. Но как то же самое получить с этим приложением?

**Comment by Nik-mmzd** [comment]
@dovecoteescapee please pin this issue, maybe this will help with "youtube is slow" duplicates

**Comment by Sicquze** [comment]
Для меня работает такой конфиг, видео грузится сразу, и нет зависаний (должно работать с провайдером мтс, как я думаю)
DNS: 8.8.8.8
Listen address: 127.0.0.1
Maximum number of connection: 512
Buffer size: 16384
Default TTL: 0
No domain: false
Desync only HTTPS and TLS: true
Desins method: Disorder
Split position: 1
Split at host: false
TTL of fake packets: 7
SNI of fake packet: www.iana.org
OOB Data: a
Host mixed case: false
Domain mixed case: false
Host remove spaces: false
Split TLS record: false
TLS record split position: 1
Split TLS record at SNI: true

**Comment by Gor500** [comment]
> Для меня работает такой конфиг, видео грузится сразу, и нет зависаний (должно работать с провайдером мтс, как я думаю) DNS: 8.8.8.8 Listen address: 127.0.0.1 Maximum number of connection: 512 Buffer size: 16384 Default TTL: 0 No domain: false Desync only HTTPS and TLS: true Desins method: Disorder Split position: 1 Split at host: false TTL of fake packets: 7 SNI of fake packet: [www.iana.org](http://www.iana.org) OOB Data: a Host mixed case: false Domain mixed case: false Host remove spaces: false Split TLS record: false TLS record split position: 1 Split TLS record at SNI: true

Красава чел, уже неделю ищу рабочий конфиг, все что до этого писали в обсуждении не работало, щас наконец то заработало, грузит сразу, даже в 2К, лучший, у меня Ростелеком :)

**Comment by denmorgenshtern** [comment]
> Для меня работает такой конфиг

действительно один из лучших вариантов, спасибо!

Дочка ростелекома.

Все еще есть долгий старт, в 3-5с при перемотке, и иногда буфер заполняется на пару секунду и еще висит 3-5с, но потом доходит аж до 100с, чего не было ни с одним вариантом 🤘

**Comment by icynstant** [comment]
> Для меня работает такой конфиг, видео грузится сразу, и нет зависаний (должно работать с провайдером мтс, как я думаю)

Мне не помогло. Только несколько первых кадров грузит и всё

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждения, не относящиеся к разработке в discussions #62
