### ISSUE TITLE
Не получается скачать файл 

### ISSUE THREAD

**Issue by Fat-Goblin** [dovecoteescapee/ByeDPIAndroid#24]
Я попытался скачать файл, но выскочила ошибка такого характера 
![Screenshot_2024-08-02-12-00-34-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a07c7b13-893a-4d00-a653-a92f404fbe43)

**Comment by KiGamji** [comment]
https://github.com/dovecoteescapee/ByeDPIAndroid/releases/download/1.0.0/byedpi-1.0.0.apk

**Comment by dovecoteescapee** [comment]
You can download application from Releases
https://github.com/dovecoteescapee/ByeDPIAndroid/releases
