### ISSUE TITLE
Это что такое?

### ISSUE THREAD

**Issue by Pasha33Pro** [dovecoteescapee/ByeDPIAndroid#25]
https://www.virustotal.com/gui/file/f540f3ff4ff1c89ae9579b7773bf19411f9d9a6c1e60ad231020dfe13df14b03

**Comment by KiGamji** [comment]
https://github.com/dovecoteescapee/ByeDPIAndroid/issues/5

**Comment by dovecoteescapee** [comment]
Fixed
https://www.virustotal.com/gui/file/763986ea581968d34c1aaa49fdfd4f7138172013767af9aa4a9ca8dde4b27955
