### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by hooddy** [dovecoteescapee/ByeDPIAndroid#26]
Прилжоение вполне работает на ящике, но без иконки для тв-лончера геморно его запускать из меню телевизора. можно ли добавить поддержку ящиков?

**Comment by J28zxc** [comment]
Если автор не обновит ByeDPI, то можно использовать приложение Mix-Apps. Он доступен в Google Play и открывать его можно без геморроя.

**Comment by hooddy** [comment]
> Если автор не обновит ByeDPI, то можно использовать приложение Mix-Apps. Он доступен в Google Play и открывать его можно без гемороя.

Ммм не понял. Для тупых распальцуйте плз.

**Comment by x09** [comment]
На моем TV (Xiaomi) приложение хоть и открывается, но ютуб через него вообще не работает, даже превью не грузит.

**Comment by NikittyS** [comment]
> На моем TV (Xiaomi) приложение хоть и открывается, но ютуб через него вообще не работает, даже превью не грузит.

Аналогично,  приложение ни в какую не хочет. Но при этом с браузера работает ютуб, инста и тд. Правда у меня стик realmi. Поставил SmartTube, с ним работает, попробуйте. 

РТК
Desync method - Disorder
Split position - 1

**Comment by dovecoteescapee** [comment]
duplicate #13
