### ISSUE TITLE
Autostart on boot 

### ISSUE THREAD

**Issue by ID86s** [dovecoteescapee/ByeDPIAndroid#27]
Is it possible to somehow autostart app on boot (like orbot does)?
i mean it will launch itself and automatically connect on device boot.
it will especially usefull in Meta quest 2/pro/3 hmds, or in any wifi only devices

**Comment by sidhome2021** [comment]
Please add option autostart&connect

**Comment by dovecoteescapee** [comment]
Duplicate #6
