### ISSUE TITLE
Please add instruction how to build from source

### ISSUE THREAD

**Issue by klinok64** [dovecoteescapee/ByeDPIAndroid#28]
Since this repo haven't been updated over 6 months I want to try make some changes locally for my personal use

**Comment by klinok64** [comment]
Also, I stuck at building tun2socks aar file with gomobile
I will appreciate any help

**Comment by krlvm** [comment]
IIRC you need to pass NDK to gomobile arguments to fix build

**Comment by klinok64** [comment]
I did not encounter any problems with Android NDK, wdym?
I stuck here:
`C:\1313\tun2socks> gomobile bind -androidapi 34 -v tun2socks
no exported names in the package "tun2socks"
no exported names in the package "tun2socks"
no exported names in the package "tun2socks"
no exported names in the package "tun2socks"`

Also i discovered Golang like... yesterday :)

**Comment by krlvm** [comment]
You should not invoke it manually. Is is being invoked as part of Gradle build.

**Comment by klinok64** [comment]
Oh.... thank you a lot
Did i need to build it with gradle only, or i can use Android studio?
Because Android studio states that tun2socks is missing and i need to build it|
And also gradle alone isnt working even after i specify sdk

**Comment by krlvm** [comment]
> Because Android studio states that tun2socks is missing and i need to build it

If you check the actual log you will notice that gomobile invocation failed - its arguments should be adjusted

**Comment by dovecoteescapee** [comment]
Done
https://github.com/dovecoteescapee/ByeDPIAndroid/blob/master/README.md#building
