### ISSUE TITLE
Instagram (Инстаграм) не работает

### ISSUE THREAD

**Issue by jestxfot** [dovecoteescapee/ByeDPIAndroid#29]
GoodbyeDPI позволяет на Windows оживить Инстаграм, тогда как эта программа - нет. Twitter же аналогично в этой программе почему-то работает, также как и ютуб.

С чем это может быть связано и имеет ли программа какие-то настройки?

**Comment by sidhome2021** [comment]
Попробуйте поменять в настройках программы DNS, например на 64.6.64.6

**Comment by whoizit** [comment]
У меня на оборот Instagram летает с этой штукой, а Ютюб пока не понял, 5 утра не лагает

**Comment by denmorgenshtern** [comment]
угу, как-то не все разблокируется. Инста и фб пашут прекрасно, rezka.ag и ютуб - никак.

**Comment by Dies143** [comment]
Аналогично, не работает инстаграм. Хотя пару дней назад ещё все было нормально. Смена dns на 64.6.64.6 не помогла.

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждения, не относящиеся к разработке, в discussions https://github.com/dovecoteescapee/ByeDPIAndroid/discussions/63
