### ISSUE TITLE
Не работает.

### ISSUE THREAD

**Issue by AngelKayurov** [dovecoteescapee/ByeDPIAndroid#37]
Все пишут "я установил и всё работает, ничего настраивать не надо.". У меня, на моём galaxy note 9, не работает. Включаю режим VPN в ByeDPI и у меня не загружаются видео СОВСЕМ, ПОЛНОСТЬЮ! АБСОЛЮТНО! Загружаются страницы сообщетсва, загружаюется профиль, всё работает, кроме непосредственно видео и комментариев к нему. Ну что аз приколы? Где гайд по настройке?!

P.S. использую youtube revanced, QUIC отключен, прошивка AROMA 4.1.1.

**Comment by Un-ka** [comment]
> QUIC отключен
Где и как?

**Comment by icynstant** [comment]
хватит создавать дубликаты

**Comment by lynrayy** [comment]
+
Мне это приложение просто весь инет кладёт на телефоне, даже обычные сайты не открываются. 
На компе всё работает, на телефоне в той же сети - нет. Как будто баг приложения
У меня Android 11

**Comment by bogdanmirz** [comment]
У меня тоже не заработало из коробки. Зато заработало с ютубом через веб в Хроме. Realme Note 50, Android 13. Попробуй через браузер.

> Все пишут "я установил и всё работает, ничего настраивать не надо.". У меня, на моём galaxy note 9, не работает. Включаю режим VPN в ByeDPI и у меня не загружаются видео СОВСЕМ, ПОЛНОСТЬЮ! АБСОЛЮТНО! Загружаются страницы сообщетсва, загружаюется профиль, всё работает, кроме непосредственно видео и комментариев к нему. Ну что аз приколы? Где гайд по настройке?!
> 
> P.S. использую youtube revanced, QUIC отключен, прошивка AROMA 4.1.1.

**Comment by lynrayy** [comment]
> Попробуй через браузер.

Кто нахуй будет через браузер сидеть?

**Comment by ArtZinsane** [comment]
> > Попробуй через браузер.
> 
> Кто нахуй будет через браузер сидеть?

Ну ты))

 Помогает перенастройка 
DNS:                       8.8.8.8
Mode:                      VPN
Desync only HTTPS and TLS: On
Desync method:             fake 
Split position:            1 
Split TLS record at SNI:   On

**Comment by bogdanmirz** [comment]
Спс, помогло! Только почему-то при открытии видоса и его немедленной перемотке видос загружается невероятно долго. А если открыть и смотреть с нуля, то все норм.

> Помогает перенастройка DNS: 8.8.8.8 Mode: VPN Desync only HTTPS and TLS: On Desync method: fake Split position: 1 Split TLS record at SNI: On

**Comment by icynstant** [comment]
>  Помогает перенастройка

Раньше помогал дефолт + split position 1, теперь это, а также твой и другого человека конфиги про которого говорят что рабочий, со всем этим грузит только первые пол секунды видео и всё :(

Буду с компа смотреть через RustDesk

**Comment by bogdanmirz** [comment]
> со всем этим грузит только первые пол секунды видео и всё

У меня с дефолтными так было. При этом с компа через тот же роутер норм робит с Гудбайдипиай.

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждения, не относящиеся к разработке в discussions https://github.com/dovecoteescapee/ByeDPIAndroid/discussions/62

**Comment by Individooms** [comment]
> Помогает перенастройка DNS: 8.8.8.8 Mode: VPN Desync only HTTPS and TLS: On Desync method: fake Split position: 1 Split TLS record at SNI: On

Спасибо, уважаемый!
