### ISSUE TITLE
Play protect detects it as harmful.

### ISSUE THREAD

**Issue by kotenok2000** [dovecoteescapee/ByeDPIAndroid#4]

**Comment by dovecoteescapee** [comment]
Это интересно, надо будет разобраться и поправить

**Comment by kotenok2000** [comment]
Virustotal does it too
https://www.virustotal.com/gui/file/f540f3ff4ff1c89ae9579b7773bf19411f9d9a6c1e60ad231020dfe13df14b03/relations
It especially doesn't like libgojni.so

**Comment by dovecoteescapee** [comment]
Fixed
https://www.virustotal.com/gui/file/763986ea581968d34c1aaa49fdfd4f7138172013767af9aa4a9ca8dde4b27955

**Comment by kotenok2000** [comment]
What was the reason?
