### ISSUE TITLE
Оптимальный конфиг под МТС (мобильный)

### ISSUE THREAD

**Issue by ruha9005** [dovecoteescapee/ByeDPIAndroid#41]
Чуть подкрутил https://github.com/dovecoteescapee/ByeDPIAndroid/issues/23, теперь грузит видосы в 4К и открывает заблоченные сайты
DNS: 9.9.9.9
Listen address: 0.0.0.0
Maximum number of connection: 512
Buffer size: 16384
Default TTL: 0
No domain: false
Desync only HTTPS and TLS: false
Desync method: Fake
Split position: 1
Split at host: true
TTL of fake packets: 7
SNI of fake packet: yandex.ru
OOB Data: a
Host mixed case: true
Domain mixed case: true
Host remove spaces: true
Split TLS record: true
TLS record split position: 1
Split TLS record at SNI: true.

**Comment by sviridof** [comment]
Домашний интернет от МТС.
Настроил по вашему образцу. Порт так и оставил 1080. Или нужен другой порт?

**Comment by Somov62** [comment]
Помогло - в revanced начало в 1080 грузиться. Аватарки и фоточки сообществ не появились.

**Comment by Sovietsky4el** [comment]
Бывший МГТС, а ныне МТС. Мне не помогло (

**Comment by ruha9005** [comment]
Поправил название, чтоб лишний раз не дезинформировать. По всей видимости используют разные алгоритмы.

**Comment by ZKBeat** [comment]
> Бывший МГТС, а ныне МТС. Мне не помогло (



> Домашний интернет от МТС. Настроил по вашему образцу. Порт так и оставил 1080. Или нужен другой порт?



Конфиг сработал на домашнем МТС
![20240808_020620](https://github.com/user-attachments/assets/482c980c-e7c0-4f90-92b0-3337533b1472)

**Comment by dovecoteescapee** [comment]
> Порт так и оставил 1080. Или нужен другой порт?

Порт не влияет на обход блокировок, он используется только локально

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждения, не относящиеся к разработке, в discussions https://github.com/dovecoteescapee/ByeDPIAndroid/discussions/62

**Comment by ruha9005** [comment]
@dovecoteescapee предлагаю если уж переносим обсуждения в какую-то конкретную дискуссию, то закрепить её сверху, чтобы людям не приходилось за рабочим функционалом выискивать темы обсуждений с конфигами

**Comment by dovecoteescapee** [comment]
> то закрепить её сверху

Тема про Youtube закреплена.

> чтобы людям не приходилось за рабочим функционалом выискивать темы обсуждений с конфигами

Более-менее универсальных настроек мне неизвестно. Если появится структурированная информация по разным провайдерам, то я с радостью её закреплю везде. Сейчас, мне кажется, лучше позволить людям делиться своими конфигами и обсуждать их, чем предлагать какие-то, которые будут работать с переменным успехом.

**Comment by TolEVG** [comment]
Сделайте в настройках в приложении на андроид, чтобы можно было вводить несколько вариантов настроек, так как у меня есть домашняя сеть МГТС и мобильный интернет тоже от МТС, но они требуют разных настроек....

**Comment by THEBIGMISHA** [comment]
Можно пж конфиг в виде cli флагов
