### ISSUE TITLE
Does not work on Android 7.1.2 

### ISSUE THREAD

**Issue by NiksonJD** [dovecoteescapee/ByeDPIAndroid#44]
Does not work on Android 7.1.2 TV BOX, an interface error crashes 5 seconds after the start.
0.1.1-alpha  this release does not crash , but it does not perform its functions either, YOUTUBE slows down

**Comment by dovecoteescapee** [comment]
В настоящее время приложение не поддерживает Android TV (хоть и может у кого-то успешно работать).
