### ISSUE TITLE
[Feature request] Run as root

### ISSUE THREAD

**Issue by LenaTDDS** [dovecoteescapee/ByeDPIAndroid#45]
I would like to see a slightly similar principle of operation as here: https://github.com/nomoresat/DPITunnel-android

As advantages, you can solve the problem of autorun during phone boot and the lack of need to keep the program as a VPN. Disadvantage: you will need root rights. However, I see this as an optional option, i.e. not forcing the user to use the root option.

Unfortunately, the program above has not been updated for a long time and does not always correctly bypass all dpi locks with my current ISP-operator.

**Comment by krlvm** [comment]
> autorun during phone boot

It can be achieved without root with BroadcastReceiver

**Comment by krlvm** [comment]
I don't see any features in ByeDPI used by this app that can't work on Android without root

**Comment by dovecoteescapee** [comment]
As already answered, autostart is possible without root rights, and ByeDPI does not require them. At the moment the application is a UI for ByeDPI.

**Comment by LenaTDDS** [comment]
> As already answered, autostart is possible without root rights, and ByeDPI does not require them. At the moment the application is a UI for ByeDPI.

Please re-read this part:


> I'm not worried about autorun. The bottom line is that using root rights, the program will work at a much lower level, with raw data.

This will allow you to implement more sophisticated attacks without using the application as a VPN per se. 

Moreover, this will allow me to bypass DPI and, if necessary, also connect/disconnect any VPN from above without having to constantly switch to the VPN that ByeDPI provides. 

My main thought is not about autostart

**Comment by dovecoteescapee** [comment]
> Moreover, this will allow me to bypass DPI and, if necessary, also connect/disconnect any VPN from above without having to constantly switch to the VPN that ByeDPI provides.

The application uses [ByeDPI](https://github.com/hufrea/byedpi) as a core, which does not require root rights. You suggest rewriting/replacing the core. ByeDPI copes with its functionality quite well, so I don't see the point in this.
