### ISSUE TITLE
Встроенный антивирус Trustlook бьет тревогу, обнаруживая в приложении вирус Malvare

### ISSUE THREAD

**Issue by AFKGang** [dovecoteescapee/ByeDPIAndroid#48]
Ложное срабатывание или нет?

**Comment by dovecoteescapee** [comment]
Можете прислать на что именно жалуется?
Virustotal говорит, что всё нормально
https://www.virustotal.com/gui/url/1f2be0237023bcc8fa18593c25602a75c3767c3029e74c06bf5e6ea8f8660d4c

**Comment by AFKGang** [comment]
> Можете прислать на что именно жалуется? Virustotal говорит, что всё нормально https://www.virustotal.com/gui/url/1f2be0237023bcc8fa18593c25602a75c3767c3029e74c06bf5e6ea8f8660d4c

https://www.virustotal.com/gui/file/763986ea581968d34c1aaa49fdfd4f7138172013767af9aa4a9ca8dde4b27955/detection
Что на сайте, что встроенный антивирус Trustlook выдают Malware
![Screenshot_20240808-022426](https://github.com/user-attachments/assets/388adab8-2429-4eab-a416-1a6b780c3a7a)

**Comment by AFKGang** [comment]
> > Можете прислать на что именно жалуется? Virustotal говорит, что всё нормально https://www.virustotal.com/gui/url/1f2be0237023bcc8fa18593c25602a75c3767c3029e74c06bf5e6ea8f8660d4c
> 
> https://www.virustotal.com/gui/file/763986ea581968d34c1aaa49fdfd4f7138172013767af9aa4a9ca8dde4b27955/detection Что на сайте, что встроенный антивирус Trustlook выдает вредоносное ПО ![Скриншот_20240808-022426](https://private-user-images.githubusercontent.com/177791138/356031407-388adab8-2429-4eab-a416-1a6b780c3a7a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNzM0MjgsIm5iZiI6MTcyMzA3MzEyOCwicGF0aCI6Ii8xNzc3OTExMzgvMzU2MDMxNDA3LTM4OGFkYWI4LTI0MjktNGVhYi1hNDE2LTFhNmI3ODBjM2E3YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QyMzI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGE5ODM0NjEwZGZlN2IxNDAwZTM5YmU2YjQ2NzM2NTk1YmY2YTRhNWNiMzBiY2Y3MDMxODk5MTFlYmM3MzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vD8AFOmCMEgWxYi2JNCL3pU6ZooJAyynveywsWzccZw)

При том что я скачивал не со стороннего ресурса, а здесь

**Comment by dovecoteescapee** [comment]
Перепроверил, если загрузить файл virustotal действительно ругается. Проблема та же, что и [раньше](https://github.com/dovecoteescapee/ByeDPIAndroid/issues/5#issuecomment-2187601061). Перед публикацией я проверил и всё было хорошо. Честно говоря, не понимаю, почему ему не нравится этот файл

**Comment by AFKGang** [comment]
> Перепроверил, если загрузить файл virustotal действительно ругается. Проблема та же, что и [раньше](https://github.com/dovecoteescapee/ByeDPIAndroid/issues/5#issuecomment-2187601061). Перед публикацией я проверил и всё было хорошо. Честно говоря, не понимаю, почему ему не нравится этот файл

Да я и сам не понимаю с чем может быть связано такое срабатывание от Virustotal. В любом случае успехов в исправлении в будущих обновлениях!

**Comment by dovecoteescapee** [comment]
Завтра выпущу версию, использующую оригинальный tun2socks. Может это поможет

**Comment by dovecoteescapee** [comment]
Выпустил, но лучше не стало
https://www.virustotal.com/gui/file/c5795b6dbdd9369a440f7b2484c5826d4a900b5c6c72e7c8e1c5f9682889c716/detection

> Завтра выпущу версию, использующую оригинальный tun2socks. Может это поможет

**Comment by dovecoteescapee** [comment]
Перенёс обсуждение сюда
https://github.com/dovecoteescapee/ByeDPIAndroid/issues/61
