### ISSUE TITLE
Vierustotal detects libgojni.so as malicious

### ISSUE THREAD

**Issue by kotenok2000** [dovecoteescapee/ByeDPIAndroid#5]
https://www.virustotal.com/gui/file/f540f3ff4ff1c89ae9579b7773bf19411f9d9a6c1e60ad231020dfe13df14b03/relations

**Comment by dovecoteescapee** [comment]
Данный файл генерируется [gomobile](https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile). Я компилирую им популярную библиотеку [tun2socks](https://github.com/dovecoteescapee/tun2socks/tree/da7fa48a3784a5dca6714d4734a3eb3b181a96aa), точнее свой форк с [незначительными изменениями](https://github.com/xjasonlyu/tun2socks/compare/main...dovecoteescapee:tun2socks:main).

**Comment by kotenok2000** [comment]
Can it be fixed?

**Comment by dovecoteescapee** [comment]
> Can it be fixed?

I will try

**Comment by dovecoteescapee** [comment]
Fixed
https://www.virustotal.com/gui/file/763986ea581968d34c1aaa49fdfd4f7138172013767af9aa4a9ca8dde4b27955

**Comment by dovecoteescapee** [comment]
Перенёс обсуждение сюда
https://github.com/dovecoteescapee/ByeDPIAndroid/issues/61
