### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by lynrayy** [dovecoteescapee/ByeDPIAndroid#53]
Последняя версия. 
При попытке включить пропадет интернет во всех приложениях вообще. 

Дано: 
Мобильный интернет йота
Домашний интернет ростелеком

Мобильное приложение не работает ни на одном. 
GoodbyeDPI на пк работает. 
Т.е как минимум бай должен работает на домашнем интернете, но он не работает ВООБЩЕ

Mi9, android 11

**Comment by sidhome2021** [comment]
Домашний интернет ростелеком ЦЕНТР - работает прекрасно на дефолтных настройках (YouTube)

**Comment by dovecoteescapee** [comment]
Включите, попробуйте открыть какой-нибудь сайт, сохраните логи (в главном меню: три точки -> save logs) и пришлите их мне dovecoteescapee@cock.email

**Comment by XDeVAlien** [comment]
Попробуй настройки ниже, МТС домашний и мобильный интернет - youtube работает:
```
DNS: 77.88.8.8
Listen address: 127.0.0.1
Maximum number of connection: 512
Buffer size: 16384
Default TTL: 0
No domain: false
Desync only HTTPS and TLS: false
Desync method: out-of-band или disorder
Split position: 1
Split at host: false
TTL of fake packets: 8
SNI of fake packet: rutube.ru
OOB Data: a
Host mixed case: false
Domain mixed case: false
Host remove spaces: false
Split TLS record: true
TLS record split position: 1
Split TLS record at SNI: true
```

**Comment by TaPo4eK228** [comment]
@XDeVAlien спасибо, мне помогло. у меня вай фай РТК, до вас не работало, я поменял пункты DNS, Split position и TLS record split position и оно заработало!

**Comment by sidhome2021** [comment]
Android TV youtube на МТС домашний: BuyDPI в дефолт + Split position :1 + SmartTube beta последняя в  ней видео движок okhttp. Видео пашет в 4К на ура

**Comment by MangoShow** [comment]
> Попробуй настройки ниже, МТС домашний и мобильный интернет - youtube работает:
> 
> ```
> DNS: 77.88.8.8
> Listen address: 127.0.0.1
> Maximum number of connection: 512
> Buffer size: 16384
> Default TTL: 0
> No domain: false
> Desync only HTTPS and TLS: false
> Desync method: out-of-band или disorder
> Split position: 1
> Split at host: false
> TTL of fake packets: 8
> SNI of fake packet: rutube.ru
> OOB Data: a
> Host mixed case: false
> Domain mixed case: false
> Host remove spaces: false
> Split TLS record: true
> TLS record split position: 1
> Split TLS record at SNI: true
> ```спасибо, сработало

**Comment by lainell** [comment]
@XDeVAlien а куда вводить?
DNS: 77.88.8.8
Listen address: 127.0.0.1
Maximum number of connection: 512
Buffer size: 16384
Default TTL: 0
No domain: false
Desync only HTTPS and TLS: false
Desync method: out-of-band или disorder
Split position: 1
Split at host: false
TTL of fake packets: 8
SNI of fake packet: rutube.ru
OOB Data: a
Host mixed case: false
Domain mixed case: false
Host remove spaces: false
Split TLS record: true
TLS record split position: 1
Split TLS record at SNI: true

**Comment by dovecoteescapee** [comment]
@lainell укажите эти настройки в приложении

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждение сюда #77

**Comment by s089** [comment]
> TaPo4eK228

Спасибо 🙏
