### ISSUE TITLE
Не обходит блокировку instagram

### ISSUE THREAD

**Issue by L1nixhvh** [dovecoteescapee/ByeDPIAndroid#55]
Работает все: twiter(X), facebook, youtube. На телефоне instagram не грузит, а вот на компе с goodbyedpi все работает. В чем может быть дело?

**Comment by dovecoteescapee** [comment]
У instagram заблокированы многие ip. Попробуйте другой DNS. В идеале прописать работающие ip в hosts, но это будет возможно после того, как я закрою https://github.com/dovecoteescapee/ByeDPIAndroid/issues/51

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждения, не относящиеся к разработке, в discussions https://github.com/dovecoteescapee/ByeDPIAndroid/discussions/63

**Comment by dovecoteescapee** [comment]
> это будет возможно после того, как я закрою #51

Я ошибся, в ByeDPI нет такой возможности

**Comment by KainXVIII** [comment]
Bump, а то хотел матери на телефон поставить, а инстаграм как раз не пашет.
