### ISSUE TITLE
Не работает youtube

### ISSUE THREAD

**Issue by Ruslik-pro0100** [dovecoteescapee/ByeDPIAndroid#58]
Загружается Ютуб и позволяет смотреть все разделы, комментарии под видео, но сами видео даже не думают начать воспроизводиться. ХЕЛП. Провайдер мтс. Причем мобильный интернет позволяет смотреть видео, на компе я тоже смог все сделать и работает спокойно, а на телефоне нет. Xiaomi  POCO X3 Pro

**Comment by Ruslik-pro0100** [comment]
Я ещё хомячок чуть чуть и запускаю сразу из коробки, но попробовал скопировать конфиг снизу от человека для мтс как раз, поменялось только то, что спустя минут 6 загрузки с телефона видео все таки начало грузить, даже проматывать его можно было, однако ждать 6 минут для начала видео это долговато. Адмиин помоги родненькай.

**Comment by Ruslik-pro0100** [comment]
Версию скачал 1.0.1. Щас попробую 1.0.0 тогда

**Comment by Ruslik-pro0100** [comment]
Ладно. 1.0.0 тоже не работает. Хелп пожожи если кто разобрался.

**Comment by kaajjo** [comment]
Это обсуждается в #23. Не стоит создавать issue, если проблема уже обсуждается, это очень мусорит и путает. А что насчет конфига, то тут только руками самому подбирать значения, это зависит от слишком многих факторов и универсальных решений нет

**Comment by dovecoteescapee** [comment]
Давайте перенесём обсуждения, не относящиеся к разработке, в discussions https://github.com/dovecoteescapee/ByeDPIAndroid/discussions/62
