### ISSUE TITLE
Antivirus finds Malware

### ISSUE THREAD

**Issue by dovecoteescapee** [dovecoteescapee/ByeDPIAndroid#61]
Antiviruses complain about libgojni.so. This is a [tun2socks](https://github.com/xjasonlyu/tun2socks) library compiled for Android. I can release a version without it only with proxy mode, or replace it with another library.

---

Антивирусы ругаются на libgojni.so. Это скомпилированная под Android библиотека [tun2socks](https://github.com/xjasonlyu/tun2socks). Можно выпустить версию без неё только с режимом прокси, либо заменить на другую библиотеку.

---

https://www.virustotal.com/gui/file/c5795b6dbdd9369a440f7b2484c5826d4a900b5c6c72e7c8e1c5f9682889c716/

#5 #48 #54

**Comment by ropucyka** [comment]
Автор гляди https://github.com/heiher/hev-socks5-tunnel?tab=readme-ov-file#benchmarks
Я не разбираюсь, но по картинкам та штука похоже быстрее и возможно не дёргает антивирусы.

**Comment by jim2310** [comment]
Странно работает, без запуска ютуб приложение не грузится совсем или грузится очень долго, после запуска превью в приложении ютуб подгружаются моментально, при запуске ролика прогружается 9 секунд видео и дальше не идет, иногда попадаю на ролик который можно посмотреть, чем отловить проблему?

**Comment by dovecoteescapee** [comment]
@jim2310 этот issue посвящён другой теме

**Comment by dovecoteescapee** [comment]
Fixed by replacing tun2socks with hev-socks5-tunnel

---

Исправлено заменой tun2socks на hev-socks5-tunnel

---

https://www.virustotal.com/gui/file/2ae7bac7297cd4ce72975bce950c08b1baff6e7b028ad341e6ee2970fc18964b

**Comment by kirsan31** [comment]
@dovecoteescapee c сегодняшнего дня, МС антивирус (встроенный и на вирустотал) стал детектить такую штуку в 1.2.0: [Trojan:Script/Wacatac.B!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503):

**Comment by icynstant** [comment]
Встроенный антивирус самсунга говорит что вирус

**Comment by icynstant** [comment]
Встроенный антивирус Samsung McAfee видит как вирус. Прошу заменить на другую библиотеку

**Comment by icynstant** [comment]
Встроенный антивирус Samsung McAfee видит как вирус
