### ISSUE TITLE
Как скачать?

### ISSUE THREAD

**Issue by Nelimu5221** [dovecoteescapee/ByeDPIAndroid#66]
Это помому вирус имеющий какой то анлокер я хс но я хотел 
скачать через андройд тв

**Comment by RazerStvH** [comment]
Родный, ты что тут забыл? Сомневаешься - вперед анализировать код!

**Comment by dovecoteescapee** [comment]
Скачать можно в https://github.com/dovecoteescapee/ByeDPIAndroid/releases. Ссылка на последнюю версию: https://github.com/dovecoteescapee/ByeDPIAndroid/releases/download/1.0.2-rc1/byedpi-1.0.2-rc1.apk.
