### ISSUE TITLE
err_proxy_connection_failed

### ISSUE THREAD

**Issue by Asyaleyb** [dovecoteescapee/ByeDPIAndroid#67]
After using this app and deleting it, internet got completely broke down, neither WiFi of mobile data is working. In chrome I get err_proxy_connection_failed. Tried to delete adguard, didn't work. All proxy settings are on default.Made network settings reset. Nothing helps. Not a single app works except of WhatsApp and telegram. Any hints how to solve this issue?

Rooted, magisk and other stuff
Android 13
OnePlus 10 pro if it'll help

**Comment by dovecoteescapee** [comment]
The application does not change network settings. It receives traffic only through VPN mode. Have you changed your proxy settings?

**Comment by Asyaleyb** [comment]
> The application does not change network settings. It receives traffic only through VPN mode. Have you changed your system proxy settings?

No proxy is set in WiFi or mobile data settings

**Comment by dovecoteescapee** [comment]
If you get this error in your browser, it means that the browser itself is trying to use a proxy. Usually browsers use a proxy from the settings. Perhaps some settings were affected on the rooted phone that are not available in the interface. What other VPN/Proxy apps have you used recently? This will help figure out what could have been changed.

**Comment by dovecoteescapee** [comment]
Do you use any of these AdGuard features?
https://adguard.com/kb/adguard-for-android/features/rooted/

**Comment by dovecoteescapee** [comment]
Try to reset proxy via adb
`adb shell settings put global http_proxy :0`
https://stackoverflow.com/questions/31807559/undo-setting-proxy-via-settings-global-in-android

**Comment by Asyaleyb** [comment]
> Try to reset proxy via adb `adb shell settings put global http_proxy :0` https://stackoverflow.com/questions/31807559/undo-setting-proxy-via-settings-global-in-android


Thx, problem solved, seems like the app somehow makes some non-reversable proxy settings

**Comment by dovecoteescapee** [comment]
Please describe your problem in #68. This will help us find the cause.
