### ISSUE TITLE
Инстаграм

### ISSUE THREAD

**Issue by Makaroffykt** [dovecoteescapee/ByeDPIAndroid#69]
Добрый день, ютюб заработал на дефолтных настройках, оператор мегавонь, инстаграм тоже заработал, лента открывается но нп грузит картинки и видео, комменты и описание загружает, может в настройках полазить, что отредактировать подскажите.

**Comment by dovecoteescapee** [comment]
По вопросам не относящимся к разработке пишите в [discussions](https://github.com/dovecoteescapee/ByeDPIAndroid/discussions)
