### ISSUE TITLE
Some hosts are unreachable

### ISSUE THREAD

**Issue by VEGAMETA** [dovecoteescapee/ByeDPIAndroid#70]
It just doesn't connect to some ips 157.240.205.x, e.g., 157.240.205.63 (ip of instagram) so it doesn't play any videos.

What in logs:
08-10 10:49:53.711 18945 19362 I GoLog   : time="2024-08-10T07:49:53Z" level=warning msg="[TCP] dial 157.240.205.63:443: CONNECT: host unreachable"

This problem I ran into on Samsung device (s21), my second device Xiaomi (Mi10) is working sometimes with other servers
157.240.205.175:5222 is OK
157.240.205.21:443 is OK 
157.240.205.34:443 No 
157.240.205.63:443 No
157.240.205.11:443 No

Settings I have on both devices (besides default):
DNS 8.8.8.8 
Desync method - Fake 
Split position - 1
TTL of fake packets - 1
SNI of fake packet - w3.org
Split TSL record - on
TSL record split position - 3

Проблема с подключением к определенному серверу, в моём случае инстаграмовского, поставляющего видео. Всё что при этом пишет в логах и свои настройки я указал выше.
Проблема возникла при подключении к wi-fi домашнего интернета от провайдера МТС, причём к мобильной сети от МТС любой инст сервер грузится с изменением TTL of fake packets на 4.

Я проверил, эти ipшники не пингуются даже, хотя другие рабочие инстаграмоские пингуются. Я не могу разобраться как правильно всё настроить, или дело не в настройках, ведь с goodbyedpi на ПК (домашний интернет МТС, флаги -9 -e1 -f1) та же проблема. некоторые сайты заблочены заблочены, а некоторые нет, некоторые (по wi-fi) с ByeDPIAndroid заблочены, а некоторые нет (отличны от тех, что не заблочены через goodbyedpi) и я не понимаю от чего это зависит.

Если не сложно, хотелось бы какого-то небольшого разъяснения обывателю, и, может, подсказок в более корректных настройках(хоть и тыкался я в них прилично[около суток]).

**Comment by dovecoteescapee** [comment]
Упрощая есть два подхода к блокировкам:
1. Блокировка IP
2. Блокировка на основе анализа пакетов

ByeDPI, GoodbyeDPI и другие приложения приложения позволяют обходить второй тип, но не первый. Инстаграм же в том числе блокируется по ip. Это можно попытаться явно прописав в hosts незаблокированные ip (например, [эти](https://github.com/ValdikSS/GoodbyeDPI/issues/251#issuecomment-1891254055)). Однако, для редактирования hosts на Android нужны рут права. Этот функционал может быть реализован на уровне приложения без рут прав, но в ByeDPIAndroid он не реализован.

---

Пожалуйста, вопросы не касающиеся разработки пишите в [discussions](https://github.com/dovecoteescapee/ByeDPIAndroid/discussions).
