### ISSUE TITLE
Проблема с Activity

### ISSUE THREAD

**Issue by crexlight** [dovecoteescapee/ByeDPIAndroid#71]
Описание проблемы: 
При открытии ByeDPI, переходе в настройки и открытии другого приложения (например, для чтения инструкции, какие значения что делают), а затем возвращении обратно в ByeDPI, при нажатии кнопки "назад" ожидается возврат на главный экран. Однако вместо этого приложение закрывается. Это временами бесит.

[Видео проблемы](https://youtu.be/7ITK9aE96Es?si=2RiIuJhaCECEbZBw)

**Comment by dovecoteescapee** [comment]
Исправлено
