### ISSUE TITLE
Preview for command line arguments

### ISSUE THREAD

**Issue by Lsc0x80** [dovecoteescapee/ByeDPIAndroid#78]
Make preview for command line arguments, please
like in nekobox
/
Сделай предпросмотр для cli аргументов как в nekobox

**Comment by dovecoteescapee** [comment]
Опишите подробнее, как должен выглядеть предпросмот

**Comment by Lsc0x80** [comment]
![Image](https://github.com/user-attachments/assets/c4acb0ba-fa0e-4a41-b460-f93bccd1ad56)

**Comment by MayanKoyote** [comment]
Я правильно понимаю что такое будет выводиться только если эти аргументы были заданы вручную в 'Command line editor' -> 'Command line arguments', который надо для этого вручную же и включить до того?
Не будет ли иметь больший смысл так же "переводить" накрыженное в UI в такую строку?
Возможно такими строками обмениваться будет легче и проще чем портянками скриншотов крыжиков в UI.

Обновление: увидел что уже обсуждалось здесь: https://github.com/dovecoteescapee/ByeDPIAndroid/issues/85
