### ISSUE TITLE
Домены *.local не работают

### ISSUE THREAD

**Issue by SevereCloud** [dovecoteescapee/ByeDPIAndroid#80]
### Воспроизведение

0. Поднять в локальной сети домен `hostname.local` (например с помощью avahi)
1. На телефоне включить ByeDPI
2. Попытаться открыть на телефоне `hostname.local`

### ФР:

Не удалось найти IP адрес сервера `hostname.local`

### ОР:

ip адрес зарезолвится

**Comment by dovecoteescapee** [comment]
Укажите локальный DNS-сервер

**Comment by SevereCloud** [comment]
> Укажите локальный DNS-сервер

Резолв `*.local` доменов происходит без dns серверов через мультикаст(mDNS)

**Comment by SevereCloud** [comment]
Оказалось что `.local` [не будет работать](https://source.android.com/docs/core/ota/modular-system/dns-resolver?hl=ru#:~:text=VPN%20%D0%B8%20%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5%20%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B4%D0%BB%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B8%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%20%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D1%8B%20%D0%B8%D0%B7%20%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F%20.local.) с vpn на андроиде

> VPN и мобильные подключения для передачи данных исключены из разрешения .local.

Закрываю в пользу #40
