### ISSUE TITLE
Добавьте белый и черный список приложений

### ISSUE THREAD

**Issue by AlexByte** [dovecoteescapee/ByeDPIAndroid#88]
### What problem does your proposal solve? / Какую проблему решает ваше предложение?

Некоторые приложения перестают работать

### Describe the solution you'd like / Опишите решение, которое вы предлагаете

добавить фильтр приложения в режиме VPN

### Describe alternatives you've considered / Опишите альтернативные варианты, которые вы рассматривали

нет

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] I have verified that this feature does not already exist / Я убедился(ась), что эта функция еще не существует

**Comment by dovecoteescapee** [comment]
дубликат #40
