### ISSUE TITLE
Разрешить менять настройки, когда приложение работает

### ISSUE THREAD

**Issue by cutloose** [dovecoteescapee/ByeDPIAndroid#93]
### What problem does your proposal solve? / Какую проблему решает ваше предложение?

Нельзя менять настройки пока включён впн

### Describe the solution you'd like / Опишите решение, которое вы предлагаете

Разрешить изменять настройки, при сохранении новых настроек перезапускать сервис

### Describe alternatives you've considered / Опишите альтернативные варианты, которые вы рассматривали

Их нет

### Before you submit / Прежде чем отправить

- [X] I have searched the open and closed issues for duplicates / Я искал(а) открытые и закрытые задачи на предмет дубликатов
- [X] I have verified that this feature does not already exist / Я убедился(ась), что эта функция еще не существует

**Comment by dovecoteescapee** [comment]
Дубликат #39
